apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-gitops
resources:
- namespaces.yaml
- gitops-rbac.yaml
- datavolumes.yaml
- fedora-vm.yaml
patchesStrategicMerge:
- datavolumes-application.yaml
- fedora-vm-application.yaml
